### ISSUE TITLE
Two pot templates in language directory

### ISSUE THREAD

**Issue by mbrsolution** [Arsenal21/wp-express-checkout#13]
Hi, just want to report that I found the following two template files in the /language/ directory. 

1) wp-express-checkout
2) paypal-express-checkout

You can use the following issue as reference.

https://github.com/Arsenal21/wp-express-checkout/issues/11

Thank you

**Comment by Arsenal21** [comment]
The other POT file in the wp.org repo needed to be deleted. I have fixed this in the wp.org repo.

Thank you : )
