### ISSUE TITLE
Missing some translations strings

### ISSUE THREAD

**Issue by mbrsolution** [Arsenal21/wp-express-checkout#18]
Hello, please see the following images displaying the missing Spanish translation strings for the email settings tab.

**Email sent to buyer:**

![email-sent-to-buyer](https://user-images.githubusercontent.com/38054628/77018647-f51ec980-69c9-11ea-9825-d0509fe7e62e.jpg)

**Email sent to seller:**

![email-sent-to-seller](https://user-images.githubusercontent.com/38054628/77018651-f64ff680-69c9-11ea-98cc-d43e46edc6b4.jpg)

If you need more information, please let me know,

Thank you

**Comment by dikiyforester** [comment]
Fixed via https://github.com/Arsenal21/wp-express-checkout/commit/ef8ce17f63b55709c2a08b3947827cb01fb75b21
