### ISSUE TITLE
Add an additional CSS class to the button container

### ISSUE THREAD

**Issue by Arsenal21** [Arsenal21/wp-express-checkout#23]
Currently the checkout popup trigger button has the following CSS class:

wpec-product-buy-button

It should have another additional CSS class so the button of a particular product can be targeted easily. For example:

`<div class="wpec-product-buy-button wpec-product-buy-button-product-id-1234">`

1234 is the Product ID in this example.

**Comment by dikiyforester** [comment]
Sounds Good! 

In addition, we can add the class with the button ID if we know it at this moment.

**Comment by Arsenal21** [comment]
Yep, even better.
