### ISSUE TITLE
Product Specific Thank You Page URL option

### ISSUE THREAD

**Issue by Arsenal21** [Arsenal21/wp-express-checkout#25]
Add a product meta box to override the "Thank You" page URL on a per-product basis.

Something like the following:
![thank-you-page-metabox](https://user-images.githubusercontent.com/6433635/123019282-8d003400-d413-11eb-86bc-430dad1369cd.jpg)

Additionally, need to discuss how we can potentially offer some customization of the thank you page output via the shortcode.

**Comment by dikiyforester** [comment]
Will do.

Maybe Thank You page customization via Block would be more user-friendly. What do you think?

**Comment by Arsenal21** [comment]
Yeah that sounds interesting and should be a good solution. Do just the per-product option first though. Then the block option can be investigated at a later time (since that will be a bigger ask).

**Comment by dikiyforester** [comment]
Sure

**Comment by dikiyforester** [comment]
Added 'Thank You Page URL' Product option and shortcode attribute 'thank_you_url' to override global setting.
