### ISSUE TITLE
Integration with Simple Membership Plugin

### ISSUE THREAD

**Issue by Arsenal21** [Arsenal21/wp-express-checkout#29]
Create an integration like the following but for the Simple Membership plugin:
https://www.tipsandtricks-hq.com/wordpress-membership/membership-payments-using-the-wp-express-checkout-plugin-1987

An example of integration with the stripe payments plugin:
https://simple-membership-plugin.com/stripe-payments-plugin-integration-for-membership-payment/

**Comment by dikiyforester** [comment]
I guess this is the plugin repository https://github.com/wp-insider/simple-membership ?

**Comment by Arsenal21** [comment]
Yep. 

Github repo - https://github.com/wp-insider/simple-membership

WP.org page - https://wordpress.org/plugins/simple-membership/

**Comment by dikiyforester** [comment]
Can be closed via #30
