### ISSUE TITLE
Missing translation strings

### ISSUE THREAD

**Issue by mbrsolution** [Arsenal21/wp-express-checkout#54]
Hello, please see the following image displaying the missing Spanish translation strings when adding a new product.

![wp-express-checkout-missing-strings](https://user-images.githubusercontent.com/38054628/139620976-94113593-9a1f-4976-a3cb-07164af793f4.png)

If you need more information, please let me know,

Thank you

**Comment by dikiyforester** [comment]
Updated the POT file.
