### ISSUE TITLE
Better Transaction Result/Thank You message handling

### ISSUE THREAD

**Issue by Arsenal21** [Arsenal21/wp-express-checkout#8]
Instead of showing the Transaction Result or Thank You message in a popup, we are going to show it on a "Thank You" page.

=== Background ===
A) I have made it so when the plugin is activated, it will create a "Thank You" page with the [wpec_thank_you] shortcode as the content of the page. The URL of the thank you page can be updated via the Settings menu of the plugin also (if the site admin wants to enter the thank you page shortcode on a different page for some reason).

B) Do the git pull then deactivate and re-activate your copy of the plugin to see this.

=== Next Tasks ===
The next task to complete are the following:

1) At the moment the IPN processing script (class-wpec-process-ipn.php) adds the thank you message to the following variable so it can be shown in the popup:
`
$thank_you_msg
`
It should maybe save this message to a transient then redirect the URL to the following URL (the thank you page):
`
$settings['thank_you_url']
`
2) The [wpec_thank_you] shortcode on the thank you page can show the thank you/transaction result message. So the WPECShortcode class needs to implement this new shortcode.

3) [Cleanup work] Since the above will make it to where we no longer use the Jquery UI popup to show the thank you message, we should remove the following from the plugin:
`
wp_register_style( 'wp-ppec-jquery-ui-style', WP_PPEC_PLUGIN_URL . '/public/assets/css/smoothness/jquery-ui.min.css' );
`

**Comment by dikiyforester** [comment]
This should be redirected with an order ID URL argument. 
Transient with the order data should be saved using Order ID in the transient name. 
So when you redirect to "Thank you" with Order ID you can load correct transient by Order ID.

This looks like just an order page.

There is another approach, I can suggest:
Instead of having the "Thank you" page you can display the Order summary page to the user. The Order post is already exists and includes all necessary info.  Also, order link can be sent to the user in email, so user can return to his purchase later.

@Arsenal21 what do you think?

**Comment by Arsenal21** [comment]
@dikiyforester, Yes, absolutely. Good idea. Thank you.

For now, the "Thank you" page shortcode will show some default message and order summary. However, my ideal plan  for future is there to be a Settings field in the "Advanced" settings tab where the site admin can customize the message and details shown via the thank you page shortcode. Similar to how the "Email Body" field is.  Alternatively, something like the following will do also:
https://s-plugins.com/customize-the-thank-page-message-of-stripe-payments-plugin/

**Comment by dikiyforester** [comment]
Redirect URL includes following parameters:
1. `order_id` - the reference to the current order.
2. `_wpnonce` - nonce hash to protect the "Thank You" page from unauthorized access.

We don't use a special transient to store the message, instead we build the message on the fly using the only Order ID parameter.

The "Thank You" page uses nonce verification and therefore available for the user until their session get expired. After session expired the user can't access to that page and will get appropriate message.

**Comment by Arsenal21** [comment]
Nice!
